{% set version = "0.9.5" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  fn: lmfit-{{ version }}.tar.gz
  sha256: df5830fe78a2d2d83fc89f2f5bd3e81bee9d434d59efb505b5d6cd686b7a1631

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - emcee
    - numpy
    - python
    - scipy

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
