travis:
  secure:
    BINSTAR_TOKEN: uoyCq5XudE2T2Jq2TaheFW7Zw13CduyB0Ym6PpzKbKaS77ZGtzjgYI46aw9OB7Yr1de4sCjY9wc4BInU6BKMejCriBWHBlMgLVi7xOck8lrelyXTk4fFdUgzOWlrSF+HQOrOjhgrR0XJt9MWe7qP5/Tbr8pqPYuPIX4a4t9cp6ombwEb886boGeOjvpmdmNEsgTNnAShpEElpo1oMd/n0BGeUlA0DrT5LBPtPLUAoc/F80pOh3FszsDTZf4lKth+eSRYSqggamgo1d590NP09C8ks5od2N7xFhhTMNq1ZmTzvYhBL3JHal/fbYv1XMlmut3PbZxhpxjPLlsIfYY7CcaEaKg/gsHPvlH8YIao0BrOXpcEoNP7uthzCswdZnEHuDgugRlvXq2v2iubX9/MbENEgT0GSW/1LwwwthDcBTd8QS2YHlPZWDbhiwGzwVXmnfY48b6iEQlqwSBZVD/FO9sJcUC0UH4rHMXmSelWL0qAa1GBO2/H7kg33KsfDeohDv+jIUlZgdtySft3ksr/7dz0hIrUKjJvdiIfD6KjkHXCaMmC49BM2bZH9/aohI3Rm+dT4mXqKxL7YSPz9VQGR+5MOK8C0zekAwhfWn2xRwGublCJX4ciYxFvdYPSlSGp5LWv0tsm4SQNC+n5tv+lVDf3q08kMwEgwfGuJ4U3zFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
