travis:
  secure:
    BINSTAR_TOKEN: k7dNHzwwBt4u3MLCr+Yjs64iJBA1IhG5OsLm2oKG6EVv54qxDAu7JW2yy6+E3k20Xznyh4GEbQIgiEgIExyclrDOUDZELnfm6YhK8LYH2WynQw+UwyBr5DhxtUJlwhO9JjhMfN3mvXawlRrF1gK8p5EEthC4uFveU9/aZPlmT/1PTzGbGfsygIlm0QAetYUED5hhI/TUe20j619In5Z63MKzczfVKDQ5ixabbxf2gg5TMBc659627HVE9wpZ4rS3WK4qLiA2MjQHX5MNfd41G+BZ/MsreYEIkV7oR9hgrXKN2lMJKZI1boLFBIychIWmpcUj1ARY1fFIpGfmSuCv3jK319U16IqdweI9Hx1unxSaZ0LMNhSQDzs7EUEqLMRNw6laLnsq0S0CeqKkMkeJRUnWS+XJ6bQj+yIfTMQCKcLqzO2bHVgzgFzto4qrhN9tsZsk6FRSuxbaHWKPa+0V6eMv2al338MWOirfYByBTYmsNHXhzQV9Yf0jvy4rFqDjeC7gCr74Grk1y2IUNUqqmvHGkrTZHOXTmnRpJm1+yHgcuEE6e8EXymxxCnoaOm3Pgfr/g+YAjXKJTU/V1gMKeOWLLeIlulQwpy6m/UvU7Nf9eCAqVpcksBuPonagcIDsuuOhgDqNhBQlyjEaAJ0zGtF2rnxvsbpcKm2oJUxz/ys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
