travis:
  secure:
    BINSTAR_TOKEN: N3B+nwrsbNGxOfjaA3eX0SQhvGSS04J6/p/o1vvlx/Na8A/DFftG8nt8mEcGRFUrYMv6xLIkAw8dSgCw0FGr4YltwTPmN7Ej8rTBegind4Eel+nsH+DSry89VpqcsRYseYYVE90h2ol5odLY3LmPfMLgSWrqYvnNVXjULaAOph2EEvveWHM3n55wYHNrxez9TlLxbHFBv19rFp0wdK/uj059nQsHU0lV63HqCQwaMbNfSqyzBJxjoZlA4ibS3Z6d6qcwu1Xis+5dBwRVSSkKRCAfjHXf05fEwQRBeVYHrOYqZ03zFcLRA+N6PjBs9b23E9m2YGTCOfq7pfYsE957AIvccYW6vwgIwJSpY2BNODbW9lLLlha9uZ10Kwh9P6k9qL5BlLarrKCfMQhN2imFXoGDw6oRUh0Lrfr7MZQqzora/K5M/auE7RDvA4V/a8lVaWIecB9e8RF5dCJxjZnl+6/3s9uIbZ58Jasae25cU3Q+EPuChA1TN0STy68eLKMXMlWay59x9tUhUIEE1fQ8+H+2mvo2cHR15AuvFuKcG+IOJoHYIcpzx6Y7cHk0YoV/vEkidaj96O9Rmt+wMGuKBFIxr5P1on+JLKh8ddgBRD2Rdalcy0soFlvL1FkTygeyrpu9h6IknljWJrbNjK8wM4leIhT4dEwsr22AnMfUUX0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
